# ⚠️ The contents of `vault_generic_secret` will be will be written in cleartext to state and plan files generated by Terraform.
# see https://registry.terraform.io/providers/hashicorp/vault/latest/docs/resources/generic_secret
resource "vault_generic_secret" "test" {
  count = var.provision_test_secret ? 1 : 0

  path = "${vault_mount.kvv2.path}/${var.generic_secret_name}"

  data_json = jsonencode({
    (var.generic_secret_name) = "AW96B6"
  })
}
