---
name: "Code Quality: TFLint"

on:
  pull_request:
  push:

jobs:
  tflint:
    runs-on: ubuntu-latest

    strategy:
      # see https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstrategyfail-fast
      fail-fast: false
      matrix:
        workspaces:
          - "terraform-cloud"
          - "vault-deployment"
          - "vault-config"
          - "packer-registry"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v1
        with:
          tflint_version: latest
          github_token: ${{ secrets.GITHUB_TOKEN }}
        env:
          working-dir: "${{ matrix.workspaces }}"

      - name: Initialize TFLint
        run: tflint --init "./${{ matrix.workspaces }}"

      - name: Run TFLint
        run: tflint --format=compact "./${{ matrix.workspaces }}"
